version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    volumes:
      - zookeeper-data:/opt/zookeeper/data

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CREATE_TOPICS: "events:1:1"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/kafka:/kafka
    depends_on:
      - zookeeper

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: grocery
      MYSQL_USER: lillian
      MYSQL_PASSWORD: Password
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  receiver:
    build:
      context: ./receiver
      dockerfile: Dockerfile
    # depends_on:
    #   - kafka
    # command: >
    #   sh -c "./wait-for-it.sh kafka:9092 --timeout=60 -- python app.py"
    ports:
      - "8080:8080"
    volumes:
      - ./config/receiver/app_conf.yml:/config/app_conf.yml
      - ./config/receiver/log_conf.yml:/config/log_conf.yml
      - ./logs:/logs

  storage:
    build:
      context: ./storage
      dockerfile: Dockerfile
    depends_on:
      - db
      - kafka
    ports:
      - "8090:8090"
    volumes:
      - ./config/storage/app_conf.yml:/config/app_conf.yml
      - ./config/storage/log_conf.yml:/config/log_conf.yml
      - ./logs:/logs


  processing:
    build:
      context: ./processing
      dockerfile: Dockerfile
    depends_on:
      - storage
    ports:
      - "8100:8100"
    volumes:
      - ./config/processing/app_conf.yml:/config/app_conf.yml
      - ./config/processing/log_conf.yml:/config/log_conf.yml
      - ./logs:/logs
      - ./data/processing:/data

  analyzer:
    build:
      context: ./analyzer
      dockerfile: Dockerfile
    depends_on:
      - kafka
    ports:
      - "8110:8110"
    volumes:
      - ./config/analyzer/app_conf.yml:/config/app_conf.yml
      - ./config/analyzer/log_conf.yml:/config/log_conf.yml
      - ./logs:/logs

volumes:
  zookeeper-data:
  mysql-data:
