version: 1
datastore:
  filename: /data/data.json
scheduler:
  interval: 5
eventstores:
  search:
    url: http://storage:8090/product/search
  purchase:
    url: http://storage:8090/product/sold