
openapi: 3.0.0
info:
  description: This API provides grocery event stats
  version: "1.0.0"
  title: Stats API
  contact:
    email: lvu17@mybcit.ca

paths:
  /stats:
    get:
      summary: Gets the event stats
      operationId: app.get_stats
      description: Gets search and purchase statistics
      responses:
        '200':
          description: Successfully returned stats
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/GroceryStats'
        '404':
          description: Statistics do not exist
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

components:
  schemas:
    GroceryStats:
      type: object
      required:
        - num_search_readings
        - max_search_count
        - num_purchase_readings
        - max_purchase_count
        - last_updated
      properties:
        num_search_readings:
          type: integer
          example: 500
        max_search_count:
          type: integer
          example: 100
        num_purchase_readings:
          type: integer
          example: 400
        max_purchase_count:
          type: integer
          example: 50
        last_updated:
          type: string
          format: date-time
          example: "2025-02-05T12:39:16Z"
